# Generated by Django 4.2 on 2026-05-18 05:59

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EmotionAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "analysis_type",
                    models.CharField(
                        choices=[
                            ("text", "Text Analysis"),
                            ("voice", "Voice Analysis"),
                            ("image", "Image Analysis"),
                            ("live", "Live Analysis"),
                            ("multimodal", "Multimodal Analysis"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "emotion",
                    models.CharField(
                        choices=[
                            ("happy", "Happy"),
                            ("sad", "Sad"),
                            ("angry", "Angry"),
                            ("fear", "Fear"),
                            ("disgust", "Disgust"),
                            ("surprise", "Surprise"),
                            ("neutral", "Neutral"),
                            ("stressed", "Stressed"),
                            ("motivated", "Motivated"),
                            ("confused", "Confused"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "confidence",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ]
                    ),
                ),
                ("reasoning", models.TextField()),
                (
                    "provider_used",
                    models.CharField(
                        choices=[
                            ("gemini", "Gemini"),
                            ("groq", "Groq"),
                            ("openrouter", "OpenRouter"),
                        ],
                        max_length=20,
                    ),
                ),
                ("text_input", models.TextField(blank=True, null=True)),
                ("voice_transcript", models.TextField(blank=True, null=True)),
                (
                    "image_path",
                    models.ImageField(blank=True, null=True, upload_to="analyses/"),
                ),
                ("raw_response", models.JSONField(default=dict)),
                ("suggestions", models.JSONField(default=list)),
                ("recommendations", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("duration_ms", models.IntegerField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analyses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(blank=True, null=True, upload_to="avatars/"),
                ),
                ("bio", models.TextField(blank=True, max_length=500)),
                (
                    "theme_preference",
                    models.CharField(
                        choices=[("light", "Light"), ("dark", "Dark")],
                        default="light",
                        max_length=10,
                    ),
                ),
                ("notification_preferences", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Profile",
                "verbose_name_plural": "User Profiles",
            },
        ),
        migrations.CreateModel(
            name="Recommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "emotion",
                    models.CharField(
                        choices=[
                            ("happy", "Happy"),
                            ("sad", "Sad"),
                            ("angry", "Angry"),
                            ("fear", "Fear"),
                            ("disgust", "Disgust"),
                            ("surprise", "Surprise"),
                            ("neutral", "Neutral"),
                            ("stressed", "Stressed"),
                            ("motivated", "Motivated"),
                            ("confused", "Confused"),
                        ],
                        max_length=20,
                    ),
                ),
                ("spotify_playlists", models.JSONField(default=list)),
                ("youtube_playlists", models.JSONField(default=list)),
                ("quotes", models.JSONField(default=list)),
                ("activities", models.JSONField(default=list)),
                ("resources", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "analysis",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendation",
                        to="api.emotionanalysis",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProviderLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("gemini", "Gemini"),
                            ("groq", "Groq"),
                            ("openrouter", "OpenRouter"),
                        ],
                        max_length=20,
                    ),
                ),
                ("request_time", models.DateTimeField(auto_now_add=True)),
                ("response_time_ms", models.IntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("timeout", "Timeout"),
                            ("error", "Error"),
                        ],
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                ("tokens_used", models.IntegerField(blank=True, null=True)),
                ("cost", models.FloatField(blank=True, null=True)),
                (
                    "analysis",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="provider_logs",
                        to="api.emotionanalysis",
                    ),
                ),
            ],
            options={
                "ordering": ["-request_time"],
            },
        ),
        migrations.CreateModel(
            name="FallbackLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "primary_provider",
                    models.CharField(
                        choices=[
                            ("gemini", "Gemini"),
                            ("groq", "Groq"),
                            ("openrouter", "OpenRouter"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "fallback_provider",
                    models.CharField(
                        choices=[
                            ("gemini", "Gemini"),
                            ("groq", "Groq"),
                            ("openrouter", "OpenRouter"),
                        ],
                        max_length=20,
                    ),
                ),
                ("reason", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "analysis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fallback_logs",
                        to="api.emotionanalysis",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EmotionHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "daily_emotion",
                    models.CharField(
                        choices=[
                            ("happy", "Happy"),
                            ("sad", "Sad"),
                            ("angry", "Angry"),
                            ("fear", "Fear"),
                            ("disgust", "Disgust"),
                            ("surprise", "Surprise"),
                            ("neutral", "Neutral"),
                            ("stressed", "Stressed"),
                            ("motivated", "Motivated"),
                            ("confused", "Confused"),
                        ],
                        max_length=20,
                    ),
                ),
                ("analysis_count", models.IntegerField(default=0)),
                ("average_confidence", models.FloatField(default=0.0)),
                (
                    "dominant_emotion",
                    models.CharField(
                        choices=[
                            ("happy", "Happy"),
                            ("sad", "Sad"),
                            ("angry", "Angry"),
                            ("fear", "Fear"),
                            ("disgust", "Disgust"),
                            ("surprise", "Surprise"),
                            ("neutral", "Neutral"),
                            ("stressed", "Stressed"),
                            ("motivated", "Motivated"),
                            ("confused", "Confused"),
                        ],
                        max_length=20,
                    ),
                ),
                ("date", models.DateField(auto_now_add=True)),
                ("additional_data", models.JSONField(default=dict)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="emotion_history",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="AdminLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "admin_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="admin_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.AddIndex(
            model_name="providerlog",
            index=models.Index(
                fields=["provider", "-request_time"],
                name="api_provide_provide_b91066_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="providerlog",
            index=models.Index(fields=["status"], name="api_provide_status_76cafd_idx"),
        ),
        migrations.AddIndex(
            model_name="emotionhistory",
            index=models.Index(
                fields=["user", "-date"], name="api_emotion_user_id_bf5b56_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="emotionhistory",
            unique_together={("user", "date")},
        ),
        migrations.AddIndex(
            model_name="emotionanalysis",
            index=models.Index(
                fields=["user", "-created_at"], name="api_emotion_user_id_e181c8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="emotionanalysis",
            index=models.Index(
                fields=["emotion"], name="api_emotion_emotion_6de4d2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="emotionanalysis",
            index=models.Index(
                fields=["provider_used"], name="api_emotion_provide_a87b94_idx"
            ),
        ),
    ]
